# Generated by Django 5.1.5 on 2025-01-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='game_date',
            field=models.DateField(),
        ),
    ]
