# Generated by Django 5.1.4 on 2025-01-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_schedule_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
