# Generated by Django 5.1.5 on 2025-01-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_team_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='headshot',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
